/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/scenarios/finals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a role-minimized projection of the finals scenario */
        get: operations["getFinalsScenario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/finals/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deterministically reseed the finals scenario without external effects
         * @description Privileged controlled-environment action. The server must suppress SMS,
         *     voice, and transportation side effects while reseeding.
         */
        post: operations["resetFinalsScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readiness-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record one readiness response and create separately owned work */
        post: operations["submitReadiness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-items/{work_item_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a guarded command to one human-owned work item */
        post: operations["commandWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transport/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the configured CareLink Partner Dispatch request
         * @description The server resolves the allowlisted pickup, destination, and provider; arbitrary public destinations are forbidden.
         */
        post: operations["createTransportRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transport/requests/{transport_request_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance, recover, or escalate the controlled transport lifecycle */
        post: operations["commandTransportRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communications/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue one allowlisted SMS through the transactional outbox */
        post: operations["queueReadinessSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communications/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue one bounded allowlisted voice call through the transactional outbox */
        post: operations["queueReadinessVoiceCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/callbacks/twilio/inbound-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive an inbound Twilio message after raw-request signature verification */
        post: operations["receiveTwilioInboundMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/callbacks/twilio/message-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive a Twilio delivery callback after raw-request signature verification */
        post: operations["receiveTwilioMessageStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/callbacks/elevenlabs/post-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive an allowlisted structured voice outcome after HMAC verification */
        post: operations["receiveElevenLabsPostCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/callbacks/elevenlabs/failure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record voice initiation or execution failure after HMAC verification */
        post: operations["receiveElevenLabsFailure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return operational metrics derived from workflow events */
        get: operations["getWorkflowMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/fhir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the generated FHIR R4 bundle and validator state */
        get: operations["getFhirEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return a versioned supportive-outreach score or an explicit unavailable result */
        get: operations["getPriorityEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Claim and process a bounded batch of due scheduled and outbox work
         * @description Called by the configured authenticated scheduler. Durable work exists in PostgreSQL before this endpoint runs.
         */
        get: operations["runScheduledWorkTick"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActorRole: "patient" | "caregiver" | "staff" | "transport_coordinator";
        CommandContext: {
            /** Format: uuid */
            scenario_id: string;
            actor_role: components["schemas"]["ActorRole"];
            idempotency_key: string;
            expected_aggregate_version: number;
        };
        ResetCommand: components["schemas"]["CommandContext"] & {
            /** @constant */
            confirmation: "RESET_FINALS_SCENARIO";
        };
        ReadinessSubmissionCommand: components["schemas"]["CommandContext"] & {
            /** @enum {string} */
            channel: "web" | "sms" | "voice";
            /** @enum {string} */
            transport_status: "confirmed" | "needs_help" | "unknown";
            clinical_concern_verbatim?: string | null;
            callback_requested: boolean;
        };
        WorkItemCommand: components["schemas"]["CommandContext"] & {
            /** @enum {string} */
            action: "assign" | "acknowledge" | "accept" | "request_information" | "record_action" | "escalate" | "inform_patient" | "acknowledge_patient" | "close";
            owner_id?: string | null;
            note?: string | null;
            closure_evidence?: string | null;
        };
        CreateTransportRequestCommand: components["schemas"]["CommandContext"] & {
            /** Format: uuid */
            work_item_id: string;
            treatment_arrival_window: components["schemas"]["TimeWindow"];
            /** Format: date-time */
            notice_cutoff: string;
            /** @enum {string} */
            funding_path: "pilot_sponsored" | "hospital_supported" | "patient_self_pay" | "eligibility_review_required";
            service_area: string;
            mobility: components["schemas"]["MobilityNeeds"];
            outbound_plan: components["schemas"]["TripLegPlan"];
            return_plan: components["schemas"]["TripLegPlan"];
            notification_permission: boolean;
        };
        TransportCommand: components["schemas"]["CommandContext"] & {
            /** @enum {string} */
            action: "review_eligibility" | "mark_request_ready" | "offer" | "accept" | "assign_driver" | "mark_provider_unavailable" | "decline" | "cancel" | "activate_backup" | "notify_patient" | "acknowledge_patient" | "mark_en_route" | "arrive" | "pick_up" | "complete" | "mark_return_pending" | "escalate_to_navigator";
            eligible?: boolean | null;
            service_area_confirmed?: boolean | null;
            operating_window_confirmed?: boolean | null;
            outbound_plan_complete?: boolean | null;
            return_plan_complete?: boolean | null;
            driver_alias?: string | null;
            vehicle_description?: string | null;
            reason?: string | null;
            closure_evidence?: string | null;
        };
        CommunicationCommand: components["schemas"]["CommandContext"] & {
            /** @enum {string} */
            purpose: "readiness" | "fallback" | "plan_update" | "human_callback";
            /** @constant */
            destination_alias: "finals_allowlisted_phone";
        };
        CommandReceipt: {
            /** Format: uuid */
            command_id: string;
            /** @enum {string} */
            disposition: "accepted" | "replayed";
            /** Format: uuid */
            scenario_id: string;
            /** Format: uuid */
            aggregate_id: string;
            aggregate_version: number;
            emitted_events: components["schemas"]["workflow-event.schema"][];
        };
        TimeWindow: {
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
        };
        MobilityNeeds: {
            wheelchair: boolean;
            transfer_assistance: boolean;
            escort_required: boolean;
            notes?: string | null;
        };
        TripLegPlan: {
            /** @enum {string} */
            location_alias: "maria_home" | "benson_cancer_center";
            window: components["schemas"]["TimeWindow"];
            /** @default false */
            duration_uncertain: boolean;
        };
        RoleProjection: components["schemas"]["PatientProjection"] | components["schemas"]["CaregiverProjection"] | components["schemas"]["StaffProjection"] | components["schemas"]["TransportProjection"];
        ProjectionBase: {
            /** Format: uuid */
            scenario_id: string;
            scenario_version: number;
            role: components["schemas"]["ActorRole"];
            /** Format: date-time */
            as_of: string;
            treatment: components["schemas"]["TreatmentSummary"];
            /** @enum {string} */
            readiness_status: "not_started" | "at_risk" | "action_in_progress" | "continuity_plan_confirmed";
        };
        PatientProjection: components["schemas"]["ProjectionBase"] & {
            /** @constant */
            role: "patient";
            patient: components["schemas"]["PatientSummary"];
            blockers: components["schemas"]["PatientBlocker"][];
            next_action: string | null;
            communications: components["schemas"]["CommunicationSummary"][];
            transport: components["schemas"]["PatientTransportSummary"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "patient";
        };
        /** @description Allowlisted logistics projection. When permission is revoked, transport is absent at the server boundary. Clinical text, clinical work, nurse notes, scores, and evidence are not members of this schema. */
        CaregiverProjection: components["schemas"]["ProjectionBase"] & ({
            /** @constant */
            role: "caregiver";
            caregiver: {
                display_name: string;
            };
            permission: {
                /** @constant */
                transport_logistics_allowed: true;
            };
            transport: components["schemas"]["CaregiverTransportSummary"];
        } | {
            /** @constant */
            role: "caregiver";
            caregiver: {
                display_name: string;
            };
            permission: {
                /** @constant */
                transport_logistics_allowed: false;
            };
        }) & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "caregiver";
        };
        StaffProjection: components["schemas"]["ProjectionBase"] & {
            /** @constant */
            role: "staff";
            patient: components["schemas"]["PatientSummary"];
            barriers: components["schemas"]["BarrierSummary"][];
            work_items: components["schemas"]["WorkItemSummary"][];
            communications: components["schemas"]["StaffCommunicationSummary"][];
            transport: components["schemas"]["StaffTransportSummary"];
            timeline: components["schemas"]["workflow-event.schema"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "staff";
        };
        /** @description Fulfillment projection with only trip, mobility, contact-alias, and acknowledgment data. */
        TransportProjection: components["schemas"]["ProjectionBase"] & {
            /** @constant */
            role: "transport_coordinator";
            request: components["schemas"]["TransportCoordinatorRequest"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "transport_coordinator";
        };
        TreatmentSummary: {
            /** Format: uuid */
            treatment_id: string;
            /** Format: date-time */
            starts_at: string;
            arrival_window: components["schemas"]["TimeWindow"];
            location_display_name: string;
            /** Format: date-time */
            transport_notice_cutoff: string;
        };
        PatientSummary: {
            /** Format: uuid */
            patient_id: string;
            display_name: string;
        };
        PatientBlocker: {
            /** Format: uuid */
            barrier_id: string;
            label: string;
            /** @enum {string} */
            status: "open" | "in_progress" | "awaiting_patient" | "resolved";
            owner_role: string;
            /** Format: date-time */
            due_at: string;
        };
        BarrierSummary: {
            /** Format: uuid */
            barrier_id: string;
            /** @enum {string} */
            barrier_type: "clinical_concern" | "transportation" | "scheduling" | "communication";
            /** @enum {string} */
            status: "open" | "in_progress" | "resolved" | "escalated";
            source: string;
            patient_verbatim?: string | null;
        };
        WorkItemSummary: {
            /** Format: uuid */
            work_item_id: string;
            /** @enum {string} */
            work_item_type: "clinical_review" | "transport_navigation" | "human_callback" | "scheduling_support";
            /** @enum {string} */
            owner_role: "triage_nurse" | "navigator" | "transport_coordinator" | "scheduling_team";
            owner_display_name?: string | null;
            /** @enum {string} */
            status: "open" | "assigned" | "acknowledged" | "needs_information" | "accepted" | "actioned" | "patient_informed" | "patient_acknowledged" | "escalated" | "closed";
            /** Format: date-time */
            due_at: string;
            aggregate_version: number;
            next_action?: string | null;
            closure_evidence?: string | null;
        };
        CommunicationSummary: {
            /** Format: uuid */
            communication_id: string;
            /** @enum {string} */
            channel: "sms" | "voice";
            /** @enum {string} */
            purpose: "readiness" | "fallback" | "plan_update" | "human_callback";
            /** @enum {string} */
            status: "queued" | "sent" | "delivered" | "undelivered" | "answered" | "no_answer" | "failed" | "opted_out" | "completed" | "outcome_unknown";
            /** @enum {string} */
            provenance: "provider_callback" | "deterministic_replay";
            /** Format: date-time */
            occurred_at?: string;
            reconciliation?: components["schemas"]["ProviderReconciliationSummary"];
        };
        StaffCommunicationSummary: components["schemas"]["CommunicationSummary"] & {
            reconciliation: components["schemas"]["ProviderReconciliationSummary"];
        };
        /** @description Durable provider-attempt state. Outcome-unknown work cannot be blindly resent; only the declared recovery is permitted. */
        ProviderReconciliationSummary: {
            /** @enum {string} */
            state: "not_required" | "outcome_unknown" | "reconciliation_required" | "reconciled" | "manual_recovery_required";
            /** Format: date-time */
            last_attempt_at: string | null;
            attempt_reference: string | null;
            /** @enum {string} */
            provenance: "none" | "provider_callback" | "provider_lookup" | "deterministic_replay" | "manual_recovery";
            /** @enum {string} */
            permitted_recovery: "none" | "await_callback" | "refresh_status" | "reconcile_provider" | "activate_backup" | "escalate_manually";
        };
        PatientTransportSummary: {
            status: components["schemas"]["TransportStatus"];
            provider_display_name: string;
            pickup_window?: components["schemas"]["TimeWindow"];
            return_window?: components["schemas"]["TimeWindow"];
            driver_alias?: string | null;
            vehicle_description?: string | null;
            plan_version: number;
            acknowledgment_required: boolean;
        };
        CaregiverTransportSummary: {
            status: components["schemas"]["TransportStatus"];
            provider_display_name: string;
            pickup_window?: components["schemas"]["TimeWindow"];
            return_window?: components["schemas"]["TimeWindow"];
            driver_alias?: string | null;
            vehicle_description?: string | null;
            /** @enum {string} */
            acknowledgment_status: "not_requested" | "awaiting_patient" | "acknowledged";
        };
        StaffTransportSummary: components["schemas"]["PatientTransportSummary"] & {
            /** Format: uuid */
            transport_request_id: string;
            aggregate_version: number;
            /** @enum {string} */
            eligibility: "not_reviewed" | "eligible" | "ineligible" | "needs_review";
            outbound_plan_complete: boolean;
            return_plan_complete: boolean;
            failure_reason?: string | null;
            reconciliation: components["schemas"]["ProviderReconciliationSummary"];
        };
        TransportCoordinatorRequest: {
            /** Format: uuid */
            transport_request_id: string;
            aggregate_version: number;
            status: components["schemas"]["TransportStatus"];
            arrival_window: components["schemas"]["TimeWindow"];
            /** Format: date-time */
            notice_cutoff: string;
            /** @enum {string} */
            funding_path: "pilot_sponsored" | "hospital_supported" | "patient_self_pay" | "eligibility_review_required";
            service_area: string;
            mobility: components["schemas"]["MobilityNeeds"];
            outbound_plan: components["schemas"]["TripLegPlan"];
            return_plan: components["schemas"]["TripLegPlan"];
            notification_permission: boolean;
            /** @constant */
            contact_alias?: "finals_allowlisted_phone";
            /** @enum {string} */
            acknowledgment_status: "not_requested" | "awaiting_patient" | "acknowledged";
            driver_alias?: string | null;
            vehicle_description?: string | null;
            reconciliation: components["schemas"]["ProviderReconciliationSummary"];
        };
        /** @enum {string} */
        TransportStatus: "need_detected" | "eligibility_reviewed" | "request_ready" | "offered" | "accepted" | "driver_assigned" | "patient_notified" | "patient_acknowledged" | "en_route" | "arrived" | "picked_up" | "completed" | "declined" | "cancelled" | "provider_unavailable" | "outcome_unknown" | "stale_assignment" | "return_pending" | "backup_required" | "backup_activated" | "escalated_to_navigator";
        TwilioInboundMessage: {
            MessageSid: string;
            From: string;
            To: string;
            Body: string;
        } & {
            [key: string]: unknown;
        };
        TwilioMessageStatus: {
            MessageSid: string;
            /** @enum {string} */
            MessageStatus: "queued" | "sent" | "delivered" | "undelivered" | "failed";
            ErrorCode?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Official signed ElevenLabs post-call transcription envelope. Transcript and audio content are not persisted by OncoReady. */
        ElevenLabsPostCall: {
            /** @constant */
            type: "post_call_transcription";
            event_timestamp: number;
            data: {
                agent_id: string;
                conversation_id: string;
                status: string;
                analysis: {
                    data_collection_results: {
                        oncoready_outcome?: components["schemas"]["ElevenLabsOutcomeResult"];
                    } & {
                        [key: string]: unknown;
                    };
                } & {
                    [key: string]: unknown;
                };
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        ElevenLabsOutcomeResult: {
            /** @constant */
            data_collection_id: "oncoready_outcome";
            /** @enum {string} */
            value: "ready" | "ride_help" | "scheduling_help" | "human_callback" | "unsupported_or_uncertain";
            rationale?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Official signed ElevenLabs call-initiation-failure envelope. */
        ElevenLabsFailure: {
            /** @constant */
            type: "call_initiation_failure";
            event_timestamp: number;
            data: {
                agent_id: string;
                conversation_id: string;
                /** @enum {string} */
                failure_reason: "busy" | "no-answer" | "unknown";
                metadata: {
                    /** @enum {string} */
                    type: "twilio" | "sip";
                    body: {
                        [key: string]: unknown;
                    };
                } & {
                    [key: string]: unknown;
                };
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        MetricsEvidence: {
            /** Format: uuid */
            scenario_id: string;
            /** Format: date-time */
            as_of: string;
            source_event_version: number;
            lead_time_hours: number;
            time_to_owner_minutes?: number | null;
            time_to_acceptance_minutes?: number | null;
            time_to_first_action_minutes?: number | null;
            time_to_closure_minutes?: number | null;
            unresolved_blockers: {
                at_t72: number;
                at_t24: number;
                at_t4: number;
                current: number;
            };
            sla_breaches?: number;
            contact_attempts: number;
            /** @enum {string} */
            final_disposition: "kept" | "clinically_rescheduled" | "administratively_rescheduled" | "cancelled" | "unknown";
        };
        FhirEvidence: {
            /** Format: uuid */
            scenario_id: string;
            /** Format: date-time */
            generated_at: string;
            source_event_version: number;
            /** @enum {string} */
            status: "generated" | "validated" | "invalid";
            validator: {
                name: string;
                version: string;
                passed: boolean;
            };
            bundle: {
                [key: string]: unknown;
            };
            report: {
                /** @enum {string} */
                severity: "information" | "warning" | "error" | "fatal";
                message: string;
            }[];
        };
        PriorityEvidence: components["schemas"]["PriorityScoreAvailable"] | components["schemas"]["PriorityScoreUnavailable"];
        PriorityScoreAvailable: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "PriorityScoreAvailable";
            /** @constant */
            use: "supportive_outreach_ordering_only";
            model_version: string;
            feature_schema_version: string;
            feature_snapshot_hash: string;
            /** Format: date-time */
            scored_at: string;
            calibrated_probability: number;
            contributors: {
                feature: string;
                value: unknown;
                /** @enum {string} */
                direction: "increases_priority" | "decreases_priority";
                raw_margin_contribution: number;
                /** Format: date-time */
                observed_at: string;
            }[];
        };
        PriorityScoreUnavailable: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "PriorityScoreUnavailable";
            /** @constant */
            use: "supportive_outreach_ordering_only";
            /** @enum {string} */
            reason: "artifact_missing" | "artifact_malformed" | "artifact_stale" | "schema_mismatch" | "snapshot_mismatch" | "runtime_error";
        };
        OperationsTickReceipt: {
            /** Format: uuid */
            tick_id: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at: string;
            claimed: number;
            succeeded: number;
            failed: number;
            remaining_due: number;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            /** @enum {string} */
            code: "invalid_request" | "unauthorized" | "invalid_callback_signature" | "forbidden_action" | "not_found" | "version_conflict" | "invalid_transition" | "validation_failed" | "payload_too_large" | "rate_limited" | "dependency_unavailable" | "artifact_unavailable" | "internal_error";
            detail: string;
            trace_id: string;
            retryable: boolean;
            current_aggregate_version?: number | null;
        };
        scenario_reset: {
            seed_version: string;
            /** @constant */
            external_actions_suppressed: true;
        };
        readiness_submission_recorded: {
            /** Format: uuid */
            submission_id: string;
            /** @enum {unknown} */
            channel: "web" | "sms" | "voice";
            /** @enum {unknown} */
            transport_status: "confirmed" | "needs_help" | "unknown";
            clinical_concern_verbatim: string | null;
            callback_requested: boolean;
        };
        barrier_detected: {
            /** Format: uuid */
            barrier_id: string;
            /** @enum {unknown} */
            barrier_type: "clinical_concern" | "transportation" | "scheduling" | "communication";
            /** @enum {unknown} */
            source: "readiness_submission" | "sms_reply" | "voice_outcome" | "staff_action" | "scheduler";
            /** @constant */
            status: "open";
        };
        work_item_created: {
            /** Format: uuid */
            work_item_id: string;
            /** @enum {unknown} */
            work_item_type: "clinical_review" | "transport_navigation" | "human_callback" | "scheduling_support";
            /** @enum {unknown} */
            owner_role: "triage_nurse" | "navigator" | "transport_coordinator" | "scheduling_team";
            /** Format: date-time */
            due_at: string;
            /** Format: uuid */
            source_barrier_id: string;
        };
        work_item_transitioned: {
            /** Format: uuid */
            work_item_id: string;
            /** @enum {unknown} */
            from_status: "open" | "assigned" | "acknowledged" | "needs_information" | "accepted" | "actioned" | "patient_informed" | "patient_acknowledged" | "escalated";
            /** @enum {unknown} */
            to_status: "assigned" | "acknowledged" | "needs_information" | "accepted" | "actioned" | "patient_informed" | "patient_acknowledged" | "escalated" | "closed";
            owner_id?: string | null;
            note?: string | null;
            closure_evidence?: string | null;
        };
        communication_queued: {
            /** Format: uuid */
            communication_id: string;
            /** @enum {unknown} */
            channel: "sms" | "voice";
            /** @enum {unknown} */
            purpose: "readiness" | "fallback" | "plan_update" | "human_callback";
            /** @constant */
            destination_alias: "finals_allowlisted_phone";
        };
        communication_status_changed: {
            /** Format: uuid */
            communication_id: string;
            /** @enum {unknown} */
            channel: "sms" | "voice";
            /** @enum {unknown} */
            provider: "twilio" | "elevenlabs_twilio" | "deterministic_replay";
            /** @enum {unknown} */
            status: "queued" | "sent" | "delivered" | "undelivered" | "answered" | "no_answer" | "failed" | "opted_out" | "completed";
            provider_reference: string;
            failure_code?: string | null;
        };
        communication_response_recorded: {
            /** Format: uuid */
            communication_id: string;
            /** @enum {unknown} */
            channel: "sms" | "voice";
            /** @enum {unknown} */
            response_kind: "ready" | "ride_help" | "call_me" | "scheduling_help" | "repeat" | "unstructured" | "opt_out";
            verbatim_text?: string | null;
        };
        caregiver_permission_changed: {
            /** Format: uuid */
            permission_id: string;
            transport_logistics_allowed: boolean;
        };
        transport_eligibility_reviewed: {
            /** Format: uuid */
            transport_request_id: string;
            eligible: boolean;
            service_area_confirmed: boolean;
            operating_window_confirmed: boolean;
            outbound_plan_complete: boolean;
            return_plan_complete: boolean;
            reason?: string | null;
        };
        transport_status_changed: {
            /** Format: uuid */
            transport_request_id: string;
            /** @enum {unknown} */
            provider: "partner_dispatch" | "deterministic_replay";
            /** @enum {unknown} */
            from_status: "need_detected" | "eligibility_reviewed" | "request_ready" | "offered" | "accepted" | "driver_assigned" | "patient_notified" | "patient_acknowledged" | "en_route" | "arrived" | "picked_up" | "backup_required" | "backup_activated" | "return_pending";
            /** @enum {unknown} */
            to_status: "eligibility_reviewed" | "request_ready" | "offered" | "accepted" | "driver_assigned" | "patient_notified" | "patient_acknowledged" | "en_route" | "arrived" | "picked_up" | "completed" | "declined" | "cancelled" | "provider_unavailable" | "stale_assignment" | "return_pending" | "backup_required" | "backup_activated" | "escalated_to_navigator";
            driver_alias?: string | null;
            vehicle_description?: string | null;
            failure_reason?: string | null;
            closure_evidence?: string | null;
        };
        patient_plan_acknowledged: {
            /** Format: uuid */
            transport_request_id: string;
            /** @enum {unknown} */
            acknowledgment_channel: "web" | "sms" | "voice" | "staff_recorded";
            plan_version: number;
        };
        appointment_changed: {
            /** Format: date-time */
            previous_start_at: string;
            /** Format: date-time */
            new_start_at: string;
            dependent_work_reopened: boolean;
        };
        evidence_generated: {
            /** @enum {unknown} */
            evidence_type: "metrics" | "fhir_r4";
            artifact_version: string;
            /** @enum {unknown} */
            status: "generated" | "validated" | "invalid";
            validator_version?: string | null;
        };
        priority_scored: {
            model_version: string;
            feature_schema_version: string;
            feature_snapshot_hash: string;
            calibrated_probability: number;
            explanation_artifact_hash: string;
        };
        priority_score_unavailable: {
            /** @enum {unknown} */
            reason: "artifact_missing" | "artifact_malformed" | "artifact_stale" | "schema_mismatch" | "snapshot_mismatch" | "runtime_error";
        };
        envelope: {
            /** Format: uuid */
            event_id: string;
            /** @constant */
            schema_version: "1.0";
            /** Format: uuid */
            scenario_id: string;
            /** @enum {unknown} */
            aggregate_type: "scenario" | "readiness_submission" | "barrier" | "work_item" | "communication" | "transport_request" | "caregiver_permission" | "evidence" | "priority_score";
            /** Format: uuid */
            aggregate_id: string;
            aggregate_version: number;
            event_type: string;
            payload: Record<string, never>;
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            recorded_at: string;
            actor: {
                /** @enum {unknown} */
                role: "patient" | "caregiver" | "staff" | "transport_coordinator" | "system" | "provider_callback";
                actor_id: string;
            };
            /** @enum {unknown} */
            provenance: "web" | "sms" | "voice" | "twilio_callback" | "elevenlabs_callback" | "partner_dispatch" | "scheduler" | "deterministic_replay" | "reset" | "ml_pipeline";
            /** Format: uuid */
            correlation_id: string;
            /** Format: uuid */
            causation_id: string | null;
            idempotency_key?: string | null;
        };
        "$defs-scenario_reset": {
            /** @constant */
            event_type?: "scenario.reset";
            payload?: components["schemas"]["scenario_reset"];
        };
        "$defs-readiness_submission_recorded": {
            /** @constant */
            event_type?: "readiness.submission_recorded";
            payload?: components["schemas"]["readiness_submission_recorded"];
        };
        "$defs-barrier_detected": {
            /** @constant */
            event_type?: "barrier.detected";
            payload?: components["schemas"]["barrier_detected"];
        };
        "$defs-work_item_created": {
            /** @constant */
            event_type?: "work_item.created";
            payload?: components["schemas"]["work_item_created"];
        };
        "$defs-work_item_transitioned": {
            /** @constant */
            event_type?: "work_item.transitioned";
            payload?: components["schemas"]["work_item_transitioned"];
        };
        "$defs-communication_queued": {
            /** @constant */
            event_type?: "communication.queued";
            payload?: components["schemas"]["communication_queued"];
        };
        "$defs-communication_status_changed": {
            /** @constant */
            event_type?: "communication.status_changed";
            payload?: components["schemas"]["communication_status_changed"];
        };
        "$defs-communication_response_recorded": {
            /** @constant */
            event_type?: "communication.response_recorded";
            payload?: components["schemas"]["communication_response_recorded"];
        };
        "$defs-caregiver_permission_changed": {
            /** @constant */
            event_type?: "caregiver.permission_changed";
            payload?: components["schemas"]["caregiver_permission_changed"];
        };
        "$defs-transport_eligibility_reviewed": {
            /** @constant */
            event_type?: "transport.eligibility_reviewed";
            payload?: components["schemas"]["transport_eligibility_reviewed"];
        };
        "$defs-transport_status_changed": {
            /** @constant */
            event_type?: "transport.status_changed";
            payload?: components["schemas"]["transport_status_changed"];
        };
        "$defs-patient_plan_acknowledged": {
            /** @constant */
            event_type?: "patient.plan_acknowledged";
            payload?: components["schemas"]["patient_plan_acknowledged"];
        };
        "$defs-appointment_changed": {
            /** @constant */
            event_type?: "appointment.changed";
            payload?: components["schemas"]["appointment_changed"];
        };
        "$defs-evidence_generated": {
            /** @constant */
            event_type?: "evidence.generated";
            payload?: components["schemas"]["evidence_generated"];
        };
        "$defs-priority_scored": {
            /** @constant */
            event_type?: "priority.scored";
            payload?: components["schemas"]["priority_scored"];
        };
        "$defs-priority_score_unavailable": {
            /** @constant */
            event_type?: "priority.score_unavailable";
            payload?: components["schemas"]["priority_score_unavailable"];
        };
        /** OncoReady Workflow Event */
        "workflow-event.schema": {
            $defs: {
                envelope: {
                    /** Format: uuid */
                    event_id: string;
                    /** @constant */
                    schema_version: "1.0";
                    /** Format: uuid */
                    scenario_id: string;
                    /** @enum {unknown} */
                    aggregate_type: "scenario" | "readiness_submission" | "barrier" | "work_item" | "communication" | "transport_request" | "caregiver_permission" | "evidence" | "priority_score";
                    /** Format: uuid */
                    aggregate_id: string;
                    aggregate_version: number;
                    event_type: string;
                    payload: Record<string, never>;
                    /** Format: date-time */
                    occurred_at: string;
                    /** Format: date-time */
                    recorded_at: string;
                    actor: {
                        /** @enum {unknown} */
                        role: "patient" | "caregiver" | "staff" | "transport_coordinator" | "system" | "provider_callback";
                        actor_id: string;
                    };
                    /** @enum {unknown} */
                    provenance: "web" | "sms" | "voice" | "twilio_callback" | "elevenlabs_callback" | "partner_dispatch" | "scheduler" | "deterministic_replay" | "reset" | "ml_pipeline";
                    /** Format: uuid */
                    correlation_id: string;
                    /** Format: uuid */
                    causation_id: string | null;
                    idempotency_key?: string | null;
                };
                scenario_reset: {
                    /** @constant */
                    event_type?: "scenario.reset";
                    payload?: components["schemas"]["scenario_reset"];
                };
                readiness_submission_recorded: {
                    /** @constant */
                    event_type?: "readiness.submission_recorded";
                    payload?: components["schemas"]["readiness_submission_recorded"];
                };
                barrier_detected: {
                    /** @constant */
                    event_type?: "barrier.detected";
                    payload?: components["schemas"]["barrier_detected"];
                };
                work_item_created: {
                    /** @constant */
                    event_type?: "work_item.created";
                    payload?: components["schemas"]["work_item_created"];
                };
                work_item_transitioned: {
                    /** @constant */
                    event_type?: "work_item.transitioned";
                    payload?: components["schemas"]["work_item_transitioned"];
                };
                communication_queued: {
                    /** @constant */
                    event_type?: "communication.queued";
                    payload?: components["schemas"]["communication_queued"];
                };
                communication_status_changed: {
                    /** @constant */
                    event_type?: "communication.status_changed";
                    payload?: components["schemas"]["communication_status_changed"];
                };
                communication_response_recorded: {
                    /** @constant */
                    event_type?: "communication.response_recorded";
                    payload?: components["schemas"]["communication_response_recorded"];
                };
                caregiver_permission_changed: {
                    /** @constant */
                    event_type?: "caregiver.permission_changed";
                    payload?: components["schemas"]["caregiver_permission_changed"];
                };
                transport_eligibility_reviewed: {
                    /** @constant */
                    event_type?: "transport.eligibility_reviewed";
                    payload?: components["schemas"]["transport_eligibility_reviewed"];
                };
                transport_status_changed: {
                    /** @constant */
                    event_type?: "transport.status_changed";
                    payload?: components["schemas"]["transport_status_changed"];
                };
                patient_plan_acknowledged: {
                    /** @constant */
                    event_type?: "patient.plan_acknowledged";
                    payload?: components["schemas"]["patient_plan_acknowledged"];
                };
                appointment_changed: {
                    /** @constant */
                    event_type?: "appointment.changed";
                    payload?: components["schemas"]["appointment_changed"];
                };
                evidence_generated: {
                    /** @constant */
                    event_type?: "evidence.generated";
                    payload?: components["schemas"]["evidence_generated"];
                };
                priority_scored: {
                    /** @constant */
                    event_type?: "priority.scored";
                    payload?: components["schemas"]["priority_scored"];
                };
                priority_score_unavailable: {
                    /** @constant */
                    event_type?: "priority.score_unavailable";
                    payload?: components["schemas"]["priority_score_unavailable"];
                };
            };
        } & (components["schemas"]["envelope"] & (components["schemas"]["$defs-scenario_reset"] | components["schemas"]["$defs-readiness_submission_recorded"] | components["schemas"]["$defs-barrier_detected"] | components["schemas"]["$defs-work_item_created"] | components["schemas"]["$defs-work_item_transitioned"] | components["schemas"]["$defs-communication_queued"] | components["schemas"]["$defs-communication_status_changed"] | components["schemas"]["$defs-communication_response_recorded"] | components["schemas"]["$defs-caregiver_permission_changed"] | components["schemas"]["$defs-transport_eligibility_reviewed"] | components["schemas"]["$defs-transport_status_changed"] | components["schemas"]["$defs-patient_plan_acknowledged"] | components["schemas"]["$defs-appointment_changed"] | components["schemas"]["$defs-evidence_generated"] | components["schemas"]["$defs-priority_scored"] | components["schemas"]["$defs-priority_score_unavailable"]));
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid controlled-environment credential */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Provider callback signature is invalid */
        InvalidCallbackSignature: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Role or environment policy forbids this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Requested aggregate does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Expected version or transition conflicts with current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Callback exceeds the configured request-size limit */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Valid syntax but domain validation or transition guard failed */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Request rate exceeds the controlled-environment limit */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Required dependency or artifact is unavailable; no success state was recorded */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Role: components["schemas"]["ActorRole"];
        WorkItemId: string;
        TransportRequestId: string;
        TwilioSignature: string;
        ElevenLabsSignature: string;
        MaxTickItems: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getFinalsScenario: {
        parameters: {
            query: {
                role: components["parameters"]["Role"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projection for the requested local role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleProjection"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    resetFinalsScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetCommand"];
            };
        };
        responses: {
            /** @description Scenario reseeded; repeated idempotency keys replay this receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    submitReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadinessSubmissionCommand"];
            };
        };
        responses: {
            /** @description Submission accepted or idempotently replayed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    commandWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_item_id: components["parameters"]["WorkItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkItemCommand"];
            };
        };
        responses: {
            /** @description Command accepted or idempotently replayed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    createTransportRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransportRequestCommand"];
            };
        };
        responses: {
            /** @description Transport request accepted or idempotently replayed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["Unavailable"];
        };
    };
    commandTransportRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transport_request_id: components["parameters"]["TransportRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransportCommand"];
            };
        };
        responses: {
            /** @description Transport command accepted or idempotently replayed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["Unavailable"];
        };
    };
    queueReadinessSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunicationCommand"];
            };
        };
        responses: {
            /** @description SMS queued or idempotently replayed; this does not mean delivered */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["Unavailable"];
        };
    };
    queueReadinessVoiceCall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunicationCommand"];
            };
        };
        responses: {
            /** @description Call queued or idempotently replayed; this does not mean answered or completed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceipt"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            503: components["responses"]["Unavailable"];
        };
    };
    receiveTwilioInboundMessage: {
        parameters: {
            query?: never;
            header: {
                "X-Twilio-Signature": components["parameters"]["TwilioSignature"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["TwilioInboundMessage"];
            };
        };
        responses: {
            /** @description Callback accepted or duplicate safely ignored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCallbackSignature"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    receiveTwilioMessageStatus: {
        parameters: {
            query?: never;
            header: {
                "X-Twilio-Signature": components["parameters"]["TwilioSignature"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["TwilioMessageStatus"];
            };
        };
        responses: {
            /** @description Callback accepted or duplicate safely ignored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCallbackSignature"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    receiveElevenLabsPostCall: {
        parameters: {
            query?: never;
            header: {
                "ElevenLabs-Signature": components["parameters"]["ElevenLabsSignature"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElevenLabsPostCall"];
            };
        };
        responses: {
            /** @description Callback accepted or duplicate safely ignored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCallbackSignature"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    receiveElevenLabsFailure: {
        parameters: {
            query?: never;
            header: {
                "ElevenLabs-Signature": components["parameters"]["ElevenLabsSignature"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElevenLabsFailure"];
            };
        };
        responses: {
            /** @description Callback accepted or duplicate safely ignored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCallbackSignature"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    getWorkflowMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current event-derived metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsEvidence"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    getFhirEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated bundle and inspectable validation report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FhirEvidence"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    getPriorityEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Score evidence; never a clinical, eligibility, cancellation, or rescheduling decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorityEvidence"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    runScheduledWorkTick: {
        parameters: {
            query?: {
                max_items?: components["parameters"]["MaxTickItems"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded drain summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsTickReceipt"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
}
